### ISSUE TITLE
Blank/empty lines are printed on the log instead of the file paths when bulk uploading

### ISSUE THREAD

**Issue by brian-gonzalez** [MobiusHorizons/dw-utils#26] opened 2017-11-17 14:37 UTC
On version 1.3.133 and up, there seems to be an issue with file change log when bulk uploading: instead of displaying the file paths, only the "Bulk uploading X items: done" is displayed, along blank new lines for each path that should've been displayed.

Please refer to these screenshots for comparison:
- version >= 1.3.133 blank new lines: https://cl.ly/nlzx
- version <= 1.3.132 proper paths: https://cl.ly/nmdY

Hope you can look into this for the next release!

Thanks.

**Comment by MobiusHorizons** [comment] 2017-11-18 05:13
it looks to me like you are interleaving the output of some css builder with the output from `dw-utils watch`. Am I correct in this assumption? If so, how are you doing that? I may be able to test that configuration, as I suspect it is the culprit. This would be because it stores a running offset of where lines are relative to it's current position, so if another program is outputting lines to the same terminal things can go haywire. But it might also be some quirk of `Terminal` vs `iTerm2`.

**Comment by brian-gonzalez** [comment] 2017-11-20 14:33
Your assumption is very close to what I'm doing. I use [npm-run-all](https://www.npmjs.com/package/npm-run-all) to have dw-utils, webpack, and node-sass running in parallel. All three output to the console. However, this issue didn't use to exist, and as mentioned on my previous comment if I revert to dw-utils 1.3.132 the empty lines are gone.

Thanks for taking the time to look into this, and let me know if you need more information.

**Comment by MobiusHorizons** [comment] 2017-11-20 19:44
@brian-gonzalez thanks for the info. 

I understand that this is a new problem, but the lines show up correctly for me in my use case, so I'm trying to figure out what I might need to do to replicate the issue. 

That looks like a cool setup, I may have to use it myself 😄

**Comment by MobiusHorizons** [comment] 2017-11-21 21:09
whoops. I was running an older version (because of nvm). So I can easily reproduce this bug now.

**Comment by MobiusHorizons** [comment] 2017-11-28 15:54
@brian-gonzalez I finally got around to it, and it's fixed now.

**Closed as completed** 2017-11-28 15:53 UTC

**Comment by brian-gonzalez** [comment] 2017-11-28 15:58
@MobiusHorizons Thanks! Really appreciate it 👍
